### ISSUE TITLE
NullReferenceException "Object reference not set to an instance of an object." at 10/20/2025 12:18:36 PM -07:00

### ISSUE THREAD

**Issue by DeltaEon** [njthomson/SrvSurvey#465]
### What happened?

Just restarted both SRV Survey after fully closing Elite to restart it for a different error from SRV Survey. First error didn't repeat and is now replaced with this.

### Version

2.0.7.74

### Exception message

Object reference not set to an instance of an object.

### Exception stack

   at SrvSurvey.plotters.PlotBase2.renderAll(Game game, Boolean force) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\plotters\PlotBase2.cs:line 442
   at SrvSurvey.game.Game.fireUpdate(GameMode newMode, Boolean force) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 275
   at SrvSurvey.game.Game.fireUpdate(Boolean force) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 269
   at SrvSurvey.game.Game.setCurrentBody(Int32 bodyId) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 2068
   at SrvSurvey.game.Game.setLocations(Location entry, String fid, String cmdrName) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 2203
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.Game.Journals_onJournalEntry(IJournalEntry entry, Int32 index) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 1058

### Relevant log output

```shell
{"part":1,"language":"English/UK","Odyssey":true,"gameversion":"4.2.1.2","build":"r320146/r0 ","timestamp":"2025-10-20T19:08:52+00:00","event":"Fileheader"}
```

**Comment by DeltaEon** [comment]
Adding some more to this, restarting the latest build SRV Survey with Elite open instead returns this:

### Exception Stack

System.NullReferenceException: Object reference not set to an instance of an object.
   at SrvSurvey.plotters.PlotBase2.renderAll(Game game, Boolean force) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\plotters\PlotBase2.cs:line 442
   at SrvSurvey.game.Game.fireUpdate(GameMode newMode, Boolean force) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 275
   at SrvSurvey.game.Game.fireUpdate(Boolean force) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 269
   at SrvSurvey.game.Game.setCurrentBody(Int32 bodyId) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 2068
   at SrvSurvey.game.Game.setLocations(SupercruiseExit entry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 2158
   at SrvSurvey.game.Game.<>c__DisplayClass135_0.<initializeFromJournal>b__2(IJournalEntry entry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 659
   at SrvSurvey.JournalFile.walk(Int32 index, Boolean searchUp, Func`2 func) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\JournalFile.cs:line 229
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 640
   at SrvSurvey.game.Game..ctor(String cmdr) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\game\Game.cs:line 208
   at SrvSurvey.Main.newGame() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 463
   at SrvSurvey.Main.<afterMainLoad>b__18_8() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 288
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

--- End of stack trace from previous location ---
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Action method)
   at SrvSurvey.Main.<afterMainLoad>b__18_1() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 274

**Comment by njthomson** [comment]
@DeltaEon - some questions for you:

- Does this happen every time?
- Would you mind sharing the logs from SrvSurvey? They can be found in `%appdata%\SrvSurvey\SrvSurvey\1.1.0.0\logs`
- When you say *"Just restarted both SRV Survey ..."* - did you have multiple copies of SrvSurvey running?

**Comment by DeltaEon** [comment]
Every time I use the latest build it does this, only tried a handful of times before reverting to 2.0.7.20

And no, I mean I restarted both Elite: Dangerous and SRV Survey.

The three logs of version 2.0.7.74:
[srvs-20251020_120714.txt](https://github.com/user-attachments/files/23039008/srvs-20251020_120714.txt)
[srvs-20251020_120828.txt](https://github.com/user-attachments/files/23039007/srvs-20251020_120828.txt)
[srvs-20251020_122744.txt](https://github.com/user-attachments/files/23039006/srvs-20251020_122744.txt)

**Comment by njthomson** [comment]
Thanks again @DeltaEon - this comes down to a threading issue, but it _should_ be fixed in most recent builds. Please let me know if you see it again.
https://github.com/njthomson/SrvSurvey/releases/

**Comment by DeltaEon** [comment]
This happened again, version 2.0.7.81. Slightly different but still a NullReferenceException

[srvs-20251024_232825.txt](https://github.com/user-attachments/files/23139824/srvs-20251024_232825.txt)

**Comment by njthomson** [comment]
@DeltaEon - I am hopeful it is finally fixed in this build - please let me know if it happens again:
https://github.com/njthomson/SrvSurvey/releases/tag/2.0.7.83

**Comment by DeltaEon** [comment]
It's no longer throwing the error exception, but the overlay windows never render with a window handle error in the log.

Version 2.0.7.86

[srvs-20251029_122957.txt](https://github.com/user-attachments/files/23218065/srvs-20251029_122957.txt)

**Comment by DeltaEon** [comment]
Version 2.0.7.86

This error came up, wasn't present last time:

23:39:39: timer1_Tick: GetProcessesByName failed:
	Error creating window handle.
   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Form.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Form.Show(IWin32Window owner)
   at SrvSurvey.forms.FormMultiFloatie.create() in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\forms\FormMultiFloatie.cs:line 18
   at SrvSurvey.Main.timer1_Tick(Object sender, EventArgs e) in D:\a\SrvSurvey\SrvSurvey\SrvSurvey\Main.cs:line 389

[srvs-20251030_232838.txt](https://github.com/user-attachments/files/23251913/srvs-20251030_232838.txt)

**Comment by njthomson** [comment]
@DeltaEon - I've made a few fixes in this area. Let me know if you see this in a recent build:
https://github.com/njthomson/SrvSurvey/releases/

**Comment by DeltaEon** [comment]
Still getting silent errors and no overlays ingame.

version 2.0.7.98

[srvs-20251104_214107.txt](https://github.com/user-attachments/files/23351521/srvs-20251104_214107.txt)

**Comment by njthomson** [comment]
> Still getting silent errors and no overlays ingame.

What steps lead up to this error?
( This happens when starting up? Or restarting? Or closing the game with SrvSurvey running? Or ... ?)

Are you starting SrvSurvey, then closing the game in very quick succession?

**Comment by njthomson** [comment]
Actually, I think I may have found an answer. Would you mind trying the build at the bottom of this page?
https://github.com/njthomson/SrvSurvey/actions/runs/19094295277
(It may take ~10 mins to be ready)

**Comment by DeltaEon** [comment]
Can do, as for the process for trying the new builds.

Close SRVSurvey.
Fully close Elite Dangerous + launcher.

Start new version of SRVSurvey
Start Elite Launcher via steam
Login + start Elite itself
Continue + join into Canonn private group, wait a moment for stuff to load.
then start trying to view side panels and check for SRVSurvey running/errors.
Close SRVSurvey.

version 100: still getting creating window handle errors

[srvs-20251105_020931.txt](https://github.com/user-attachments/files/23357194/srvs-20251105_020931.txt)

**Comment by DeltaEon** [comment]
Went back through the versions since the version I was using that worked was 7.20.

Latest version that worked without error was 7.42.

**Comment by njthomson** [comment]
> Latest version that worked without error was 7.42.

@DeltaEon thank you for sharing - this is immensely helpful. By any chance do you run the game and/or SrvSurvey as administrator?

And do things improve it you make setting "Disable single large overlay" unchecked? (It's on tab: More)

**Comment by njthomson** [comment]
@DeltaEon - another potential fix to try:
https://github.com/njthomson/SrvSurvey/actions/runs/19122826083

Before running SrvSurvey, can you:
- Edit `%appdata%\SrvSurvey\SrvSurvey\1.1.0.0\settings.json`
- Add a line: `"disableWindowParentIsGame": true,`

This reverts a key change that happened right after the .42 build. It means the overlay windows will be always on-top, how things used to be until that point. Let me know how it goes.

**Comment by DeltaEon** [comment]
I do have to run steam in administrator, but the way elite launches the executable it never inherits administrator privileges from steam. I haven't resorted to launching everything as administrator since it was all working fine previously without.

Great news so far! Zero issues after the settings.json edit + version 101. I wonder if it's a windows 10 specific issue.

**Comment by njthomson** [comment]
I'm wondering if the game process does inherit some administratoryness - my understanding was any process spawn'd from an admin process inherits, but it's been a long time since I dealt with such things.

I am glad this new setting has things working again.

That said, I am curious what would happen if you ran SrvSurvey as administrator, just to see. Normally I would not recommend people run as administrator unless they really _really_ need to.

**Comment by DeltaEon** [comment]
What doesn't make any sense though is the "always on top" seemingly never persisted outside Elite or SrvSurvey being the current active window. If I ever tabbed into a different window, say discord or file explorer, the overlays would hide away. Now this makes the overlays persist outside the game.

I see the program auto overwrites the settings.json upon closing - so it removed the "WindowParentIsGame". Launching it as such in administrator causes no issues. So something isn't behaving as originally thought permissions wise.

**Comment by DeltaEon** [comment]
Going to try something: Disable steam overlay. I wonder if it's because it's technically an administrator permission hook, that it's locking out SrvSurvey.

**Comment by DeltaEon** [comment]
That was it. Steam overlay disabled while steam's still running in administrator lets SrvSurvey run as it should. Not a bother for me because I rarely ever touch Steam overlay in Elite specifically.

**Comment by njthomson** [comment]
>  I see the program auto overwrites the settings.json upon closing - so it removed the "WindowParentIsGame"

Only when the value is `false` - it would remain if it was `true` (it is a "hidden" setting)

**Comment by njthomson** [comment]
Closing out this old bug. Let me know if you spot any other issues.
